import React from 'react';
import {
  Box,
  Container,
  Typography,
  Paper,
  List,
  ListItem,
  ListItemText,
  Divider,
  useTheme,
} from '@mui/material';

const IntellectualPropertyPage: React.FC = () => {
  const theme = useTheme();

  return (
    <Box
      sx={{ 
        minHeight: '100vh',
        bgcolor: 'background.default',
        py: 8,
      }}
    >
      <Container maxWidth="md">
        <Paper
          elevation={3}
          sx={{
            p: 6,
            borderRadius: 3,
          }}
        >
          <Typography
            variant="h3"
            sx={{
              fontWeight: 800,
              mb: 2,
              color: theme.palette.primary.main,
              textAlign: 'center',
            }}
          >
            Intellectual Property Policy
          </Typography>
          
          <Typography
            variant="subtitle1"
            sx={{
              color: 'text.secondary',
              textAlign: 'center',
              mb: 4,
            }}
          >
            Last Updated: October 10, 2025
          </Typography>

          <Divider sx={{ mb: 4 }} />

          <Typography variant="h6" sx={{ fontWeight: 600, mb: 2 }}>
            1. CareerVista AI Intellectual Property
          </Typography>

          <Typography variant="body1" sx={{ mb: 3, lineHeight: 1.8 }}>
            CareerVista AI platform, including but not limited to the website design, 
            user interface, logos, brand names, proprietary algorithms, custom prompts, 
            database structures, and original content, are the intellectual property of 
            CareerVista AI and are protected by copyright, trademark, and other intellectual 
            property laws.
          </Typography>

          <Typography variant="h6" sx={{ fontWeight: 600, mb: 2 }}>
            2. Third-Party AI Models and Technologies
          </Typography>

          <List sx={{ mb: 3 }}>
            <ListItem>
              <ListItemText
                primary="Meta Llama Models"
                secondary="Llama 3.3 70B, Llama 3.1 8B, and other Llama variants are proprietary to Meta Platforms, Inc. Usage is governed by Meta's Custom Commercial License."
              />
            </ListItem>
            <ListItem>
              <ListItemText
                primary="Microsoft Phi Models"
                secondary="Phi-3 models are owned by Microsoft Corporation and used under their licensing terms."
              />
            </ListItem>
            <ListItem>
              <ListItemText
                primary="Mistral AI Models"
                secondary="Mistral models are owned by Mistral AI and used in compliance with their licensing agreements."
              />
            </ListItem>
            <ListItem>
              <ListItemText
                primary="Open Source Models"
                secondary="Various open-source models (Qwen, Gemma, Zephyr, OpenChat) are used under their respective open-source licenses (Apache 2.0, MIT, etc.)."
              />
            </ListItem>
          </List>

          <Typography variant="h6" sx={{ fontWeight: 600, mb: 2 }}>
            3. User Content and Data
          </Typography>

          <Typography variant="body1" sx={{ mb: 3, lineHeight: 1.8 }}>
            Users retain ownership of their personal information, academic records, and 
            content they provide to the platform. However, by using our services, users 
            grant CareerVista AI a non-exclusive, royalty-free license to use, process, 
            and analyze this data for the purpose of providing career guidance services.
          </Typography>

          <Typography variant="h6" sx={{ fontWeight: 600, mb: 2 }}>
            4. AI-Generated Content
          </Typography>

          <Typography variant="body1" sx={{ mb: 3, lineHeight: 1.8 }}>
            Content generated by AI models through our platform is not copyrightable 
            under current copyright law. However, the prompts, algorithms, and systems 
            that generate such content may be protected intellectual property. Users 
            may use AI-generated career advice for personal, non-commercial purposes.
          </Typography>

          <Typography variant="h6" sx={{ fontWeight: 600, mb: 2 }}>
            5. College and Educational Institution Data
          </Typography>

          <Typography variant="body1" sx={{ mb: 3, lineHeight: 1.8 }}>
            Information about colleges, universities, entrance exams, and scholarships 
            is compiled from publicly available sources. We respect the intellectual 
            property rights of educational institutions and provide attribution where 
            required. Official college logos, names, and proprietary information remain 
            the property of their respective institutions.
          </Typography>

          <Typography variant="h6" sx={{ fontWeight: 600, mb: 2 }}>
            6. Trademark Policy
          </Typography>

          <Typography variant="body1" sx={{ mb: 3, lineHeight: 1.8 }}>
            "CareerVista AI" and related logos are trademarks of our company. 
            Third-party trademarks mentioned on our platform (college names, 
            exam boards, etc.) are the property of their respective owners and 
            are used for informational purposes only.
          </Typography>

          <Typography variant="h6" sx={{ fontWeight: 600, mb: 2 }}>
            7. DMCA Compliance
          </Typography>

          <Typography variant="body1" sx={{ mb: 3, lineHeight: 1.8 }}>
            We respect intellectual property rights and comply with the Digital 
            Millennium Copyright Act (DMCA). If you believe your copyrighted work 
            has been used inappropriately on our platform, please contact us at 
            careervistaai@gmail.com with detailed information about the alleged infringement.
          </Typography>

          <Typography variant="h6" sx={{ fontWeight: 600, mb: 2 }}>
            8. Fair Use and Educational Purposes
          </Typography>

          <Typography variant="body1" sx={{ mb: 3, lineHeight: 1.8 }}>
            Our use of publicly available educational information and data falls 
            under fair use provisions for educational and informational purposes. 
            We strive to provide accurate, helpful information while respecting 
            the rights of content creators and institutions.
          </Typography>

          <Typography variant="h6" sx={{ fontWeight: 600, mb: 2 }}>
            9. API and Service Provider Attribution
          </Typography>

          <Typography variant="body1" sx={{ mb: 3, lineHeight: 1.8 }}>
            We acknowledge and attribute the following service providers:
          </Typography>

          <List sx={{ mb: 3 }}>
            <ListItem>
              <ListItemText primary="OpenRouter API - AI model access and routing" />
            </ListItem>
            <ListItem>
              <ListItemText primary="Google OAuth - Authentication services" />
            </ListItem>
            <ListItem>
              <ListItemText primary="MongoDB - Database services" />
            </ListItem>
            <ListItem>
              <ListItemText primary="Material-UI - User interface components" />
            </ListItem>
          </List>

          <Typography variant="h6" sx={{ fontWeight: 600, mb: 2 }}>
            10. Reporting Intellectual Property Violations
          </Typography>

          <Typography variant="body1" sx={{ mb: 3, lineHeight: 1.8 }}>
            To report intellectual property violations, please email us at 
            careervistaai@gmail.com with the following information:
          </Typography>

          <List sx={{ mb: 3 }}>
            <ListItem>
              <ListItemText primary="Description of the copyrighted work" />
            </ListItem>
            <ListItem>
              <ListItemText primary="Location of the allegedly infringing material" />
            </ListItem>
            <ListItem>
              <ListItemText primary="Your contact information" />
            </ListItem>
            <ListItem>
              <ListItemText primary="Statement of good faith belief that use is not authorized" />
            </ListItem>
            <ListItem>
              <ListItemText primary="Statement of accuracy and authority to act" />
            </ListItem>
          </List>

          <Typography variant="h6" sx={{ fontWeight: 600, mb: 2 }}>
            11. Contact Information
          </Typography>

          <Typography variant="body1" sx={{ lineHeight: 1.8 }}>
            For intellectual property questions or concerns, contact us at:<br />
            <strong>Email:</strong> careervistaai@gmail.com<br />
            <strong>Phone:</strong> +91 6301 550 164
          </Typography>

          <Divider sx={{ my: 4 }} />

          <Typography
            variant="body2"
            sx={{
              color: 'text.secondary',
              textAlign: 'center',
              fontStyle: 'italic',
            }}
          >
            This policy is subject to change. Please review regularly for updates.
          </Typography>
        </Paper>
      </Container>
    </Box>
  );
};

export default IntellectualPropertyPage;